# Generated by Django 6.0.3 on 2026-04-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('highest_education', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
                ('has_advanced_degree', models.BooleanField(default=False)),
                ('has_publications', models.BooleanField(default=False)),
                ('has_patents', models.BooleanField(default=False)),
                ('has_high_salary', models.BooleanField(default=False)),
                ('has_critical_role', models.BooleanField(default=False)),
                ('is_field_important', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
