# Generated by Django 6.0.3 on 2026-04-01 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('rule_name', models.CharField(max_length=255)),
                ('condition', models.TextField(help_text='Text or JSON logic for the condition')),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('petition_type_interest', models.CharField(choices=[('EB1A', 'EB1A'), ('EB2_NIW', 'EB2 NIW'), ('NOT_SURE', 'Not sure')], default='NOT_SURE', max_length=50)),
                ('raw_answers', models.JSONField(blank=True, default=dict)),
                ('total_score', models.IntegerField(default=0)),
                ('readiness_band', models.CharField(blank=True, max_length=100, null=True)),
                ('eb1_eligibility', models.CharField(blank=True, choices=[('LIKELY_EB1A', 'Likely EB1A'), ('LIKELY_EB2_NIW', 'Likely EB2 NIW'), ('BOTH_POSSIBLE', 'Both possible'), ('NOT_READY', 'Not ready')], max_length=50, null=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.AddField(
            model_name='categoryscore',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to='assessments.submission'),
        ),
    ]
