# Generated by Django 6.0.3 on 2026-04-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_categoryscore_scoringrule_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
