# Generated by Django 6.0.3 on 2026-04-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_add_ai_report_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='cv_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='cv_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
